# Generated by Django 4.0.2 on 2022-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
