# Generated by Django 3.2.9 on 2021-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timing',
            field=models.TextField(),
        ),
    ]
