# Generated by Django 3.2.9 on 2021-12-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211218_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
    ]
