# Generated by Django 3.2.9 on 2021-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(default='Some long para here'),
        ),
    ]
