# Generated by Django 3.2.9 on 2021-12-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211221_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.TextField(choices=[('engineer', 'ENGINEER'), ('plumber', 'PLUMBER'), ('doctor', 'DOCTOR'), ('carpenter', 'CARPENTER'), ('electrician', 'ELECTRICIAN'), ('painter', 'PAINTER'), ('barber', 'BARBER'), ('house constructor', 'HOUSE CONSTRUCTOR'), ('mason', 'MASON'), ('gardener', 'GARDENER'), ('cctv installation', 'CCTV INSTALLATION'), ('roofing & ceiling', 'ROOFING & CEILING'), ('welder', 'WELDER'), ('tailor', 'TAILOR'), ('ac/geyser installation', 'AC/GEYSER INSTALLATION'), ('mobile repair', 'MOBILE REPAIR'), ('maid', 'MAID')], max_length=255),
        ),
    ]
